# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 14:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annualHours', models.PositiveIntegerField(default=200, verbose_name='Annual hours')),
                ('typeOfPlan', models.CharField(choices=[('normal', 'Normal'), ('reversed', 'Reversed')], default='normal', max_length=20, verbose_name='Type of Plan')),
                ('planStart', models.DateField(default=datetime.date(2017, 9, 12), verbose_name='Start of Plan')),
                ('planEnd', models.DateField(default=datetime.date(2018, 9, 11), verbose_name='End of Plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aEndurance', models.PositiveSmallIntegerField(verbose_name=0)),
                ('eForce', models.PositiveSmallIntegerField(verbose_name=0)),
                ('endurance', models.PositiveSmallIntegerField(verbose_name=0)),
                ('force', models.PositiveSmallIntegerField(verbose_name=0)),
                ('gym', models.CharField(max_length=10)),
                ('maxPower', models.PositiveSmallIntegerField(verbose_name=0)),
                ('monday', models.DateField()),
                ('period', models.CharField(max_length=25)),
                ('speedSkills', models.PositiveSmallIntegerField(verbose_name=0)),
                ('test', models.PositiveSmallIntegerField(verbose_name=0)),
                ('week', models.PositiveSmallIntegerField(verbose_name=0)),
                ('weeklyHours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('races', models.CharField(max_length=300)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanWeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyHours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('day', models.PositiveIntegerField(verbose_name=0)),
                ('intensity', models.PositiveIntegerField(verbose_name=0)),
                ('workoutType', models.PositiveIntegerField(verbose_name=0)),
                ('week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.PlanWeek')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('cp60', models.PositiveIntegerField(default=100, verbose_name='CP60 (W)')),
                ('maxHR', models.PositiveIntegerField(default=180, verbose_name='Maximum Heart Rate (bpm)')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='Age')),
                ('yearsOfExperience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('strong1', models.CharField(choices=[('endurance', 'Endurance'), ('force', 'Force'), ('speedSkills', 'Speed Skills'), ('eForce', 'Endurance Force'), ('aEndurance', 'Anaerobic Endurance'), ('maxPower', 'Maximum Power')], default='endurance', max_length=30, verbose_name='Strongest skill')),
                ('strong2', models.CharField(choices=[('endurance', 'Endurance'), ('force', 'Force'), ('speedSkills', 'Speed Skills'), ('eForce', 'Endurance Force'), ('aEndurance', 'Anaerobic Endurance'), ('maxPower', 'Maximum Power')], default='endurance', max_length=30, verbose_name='Second strongest skill')),
                ('weak1', models.CharField(choices=[('endurance', 'Endurance'), ('force', 'Force'), ('speedSkills', 'Speed Skills'), ('eForce', 'Endurance Force'), ('aEndurance', 'Anaerobic Endurance'), ('maxPower', 'Maximum Power')], default='endurance', max_length=30, verbose_name='Weakest skills')),
                ('weak2', models.CharField(choices=[('endurance', 'Endurance'), ('force', 'Force'), ('speedSkills', 'Speed Skills'), ('eForce', 'Endurance Force'), ('aEndurance', 'Anaerobic Endurance'), ('maxPower', 'Maximum Power')], default='endurance', max_length=30, verbose_name='Second weakest skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2017, 9, 12, 14, 1, 57, 378832, tzinfo=utc))),
                ('name', models.CharField(default='', max_length=80)),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=(1, 'Low'), verbose_name='Priority')),
                ('time', models.TimeField(verbose_name=datetime.time(0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2017, verbose_name='Season')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Season'),
        ),
        migrations.AddField(
            model_name='plan',
            name='season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Season'),
        ),
    ]
