# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aEndurance', models.PositiveSmallIntegerField(verbose_name=0)),
                ('eForce', models.PositiveSmallIntegerField(verbose_name=0)),
                ('endurance', models.PositiveSmallIntegerField(verbose_name=0)),
                ('force', models.PositiveSmallIntegerField(verbose_name=0)),
                ('gym', models.CharField(max_length=10)),
                ('maxPower', models.PositiveSmallIntegerField(verbose_name=0)),
                ('monday', models.DateField()),
                ('period', models.CharField(max_length=25)),
                ('speedSkills', models.PositiveSmallIntegerField(verbose_name=0)),
                ('test', models.PositiveSmallIntegerField(verbose_name=0)),
                ('week', models.PositiveSmallIntegerField(verbose_name=0)),
                ('weeklyHours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('races', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PlanWeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyHours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('day', models.PositiveIntegerField(verbose_name=0)),
                ('intensity', models.PositiveIntegerField(verbose_name=0)),
                ('workoutType', models.PositiveIntegerField(verbose_name=0)),
                ('week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.PlanWeek')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=80)),
                ('priority', models.PositiveIntegerField(verbose_name=0)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='season',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='plan',
            name='annualHours',
            field=models.PositiveIntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='planEnd',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='planStart',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='typeOfPlan',
            field=models.CharField(default='regular', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cp60',
            field=models.PositiveIntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='maxHR',
            field=models.PositiveIntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='strong1',
            field=models.CharField(default='endurance', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='strong2',
            field=models.CharField(default='endurance', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='weak1',
            field=models.CharField(default='enduance', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='weak2',
            field=models.CharField(default='endurance', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='yearsOfExperience',
            field=models.PositiveIntegerField(default=3, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.User'),
        ),
        migrations.AddField(
            model_name='race',
            name='seaon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Season'),
        ),
        migrations.AddField(
            model_name='planweek',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='season_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plan.Season'),
            preserve_default=False,
        ),
    ]
