# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20170912_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 12, 14, 18, 3, 126843, tzinfo=utc)),
        ),
    ]
