# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20170801_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cp60',
            field=models.PositiveIntegerField(verbose_name='CP60'),
        ),
        migrations.AlterField(
            model_name='user',
            name='maxHR',
            field=models.PositiveIntegerField(verbose_name='Maximum Heart Rate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='strong1',
            field=models.CharField(max_length=30, verbose_name='Strongest skill'),
        ),
        migrations.AlterField(
            model_name='user',
            name='strong2',
            field=models.CharField(max_length=30, verbose_name='Second strongest skill'),
        ),
        migrations.AlterField(
            model_name='user',
            name='yearsOfExperience',
            field=models.PositiveIntegerField(verbose_name='Years of Experience'),
        ),
    ]
