# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20170801_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weak1',
            field=models.CharField(choices=[('endurance', '-'), ('endurance', 'Endurance'), ('force', 'Force'), ('speedSkills', 'Speed Skills'), ('eForce', 'Endurance Force'), ('aEndurance', 'Anaerobic Endurance'), ('maxPower', 'Maximum Power')], default='force', max_length=30, verbose_name='Weakest skills'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weak2',
            field=models.CharField(max_length=30, verbose_name='Second weakest skill'),
        ),
    ]
