# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 18:30
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20170923_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='maxHR',
            field=models.PositiveIntegerField(default=180, validators=[django.core.validators.MaxValueValidator(230)], verbose_name='Maximum Heart Rate (bpm)'),
        ),
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 23, 18, 30, 22, 657248, tzinfo=utc)),
        ),
    ]
