# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 21:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20170923_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='maxHR',
            field=models.PositiveIntegerField(default=180, verbose_name='Maximum Heart Rate (bpm)'),
        ),
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 23, 21, 2, 57, 27626, tzinfo=utc)),
        ),
    ]
