# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20170923_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='load',
            field=models.PositiveIntegerField(default=0, verbose_name='Load'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='planEnd',
            field=models.DateField(default=datetime.date(2018, 9, 30), verbose_name='End of Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='planStart',
            field=models.DateField(default=datetime.date(2017, 10, 1), verbose_name='Start of Plan'),
        ),
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 1, 18, 5, 25, 86460, tzinfo=utc)),
        ),
    ]
