# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20171001_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Duration of plan'),
        ),
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 1, 18, 7, 6, 758068, tzinfo=utc)),
        ),
    ]
